#!/usr/bin/env bash

set -e

echo "Setting up git configuration"

touch "$HOME/.gitconfig"

git config --global user.email "greg@geekingfrog.com"
git config --global user.name "Grégoire Charvet 黑瓜"
git config --global init.defaultBranch main

git config --global color.ui true
git config --global core.editor nvim

git config --global alias.st "status -sb"
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.wdiff "diff --word-diff"
git config --global alias.ls 'log --pretty format:"%C(yellow)%h %C(blue)%ad%C(red)%d %C(reset)%s%C(green) [%cn]" --decorate --date short'
git config --global alias.lsv 'log --pretty format:"%C(yellow)%h %C(blue)%ad%C(red)%d %C(reset)%s%C(green) [%cn]" --decorate --date short --numstat'
git config --global alias.lsg 'log --graph --decorate --pretty oneline --abbrev-commit --all'
git config --global alias.ps 'push --recurse-submodules check'
git config --global alias.spush 'push --recurse-submodules on-demand'
git config --global alias.supdate 'submodule update --remote --merge'

git config --global merge.tool 'vimdiff'
git config --global merge.conflictstyle 'diff3'

git config --global mergetool.keepbackup false
git config --global mergetool.prompt false

git config --global init.defaultBranch master
git config --global push.default upstream
git config --global branch.autosetuprebase always
git config --global pull.rebase merges
git config --global diff.submodule log
git config --global diff.tool difftastic

# make git pull the same git pull --recurse-submodules
git config --global submodule.recurse true
git config --global push.recurseSubmodules check

git config --global filter.lfs.clean 'git-lfs clean %f'
git config --global filter.lfs.smudge 'git-lfs smudge %f'
git config --global filter.lfs.required true

git config --global rerere.enabled true

git config --global column.ui auto
git config --global branch.sort -committerdate

# gitattribute goodness, for example:
# https://nerderati.com/tracing-the-evolution-of-a-python-function-with-git-log/
git config --global core.attributesfile "$HOME/.gitattributes"

# configure delta
if which delta >/dev/null 2>&1; then
	git config --global interactive.diffFilter "delta --color-only"
	git config --global delta.navigate true
	git config --global delta.light true
	git config --global diff.colorMoved default
	git config --global core.pager delta
fi

# configure difftastic
if which difft >/dev/null 2>&1; then
	git config --global diff.tool difftastic
	git config --global difftool.prompt false
	git config --global pager.difftool true
	git config --global difftool.difftastic.cmd 'difft "$LOCAL" "$REMOTE"'
  git config --global alias.dft difftool
fi
