[theme]
name = "modern"

[theme.overrides]
separator = ""

[icons]
name = "awesome"


[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}, {average}"

[[block]]
block = "nvidia_gpu"
label = "gpu"
show_memory = false
show_utilization = false
interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "/ {available}"
interval = 20
warning = 20.0
alert = 10.0
alert_absolute = true

[[block]]
block = "disk_space"
path = "/home/greg/extra_data"
format = "hdd {available}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "memory"
format_mem = "{mem_used}({mem_used_percents})"
format_swap = "{swap_used}({swap_used_percents})"
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"
