[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[icons.overrides]
cpu = "\uf233"


[[block]]
block = "temperature"
interval = 10
format = "$icon $average, $max"

# [[block]]
# block = "nvidia_gpu"
# # label = "gpu"
# # show_memory = false
# # show_utilization = false
# # interval = 10

[[block]]
block = "disk_space"
path = "/"
format = " / $available"
interval = 20
warning = 20.0
alert = 10.0
alert_unit = "GB"

[[block]]
block = "disk_space"
path = "/home/greg/extra_data"
format = "hdd $available"
interval = 20
warning = 20.0
alert = 10.0
alert_unit = "GB"


[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)"
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization"

[[block]]
block = "load"
interval = 2
format = " $icon $1m.eng(w:4)"

[[block]]
block = "time"
interval = 30
timezone = "Asia/Tashkent"
format = "Tashkent $timestamp.datetime(f:%R)"

[[block]]
block = "time"
interval = 30
format = "DC $timestamp.datetime(f:%R)"
timezone = "America/New_York"

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime()"
# format = "%a %d/%m %R"

[[block]]
block = "sound"
