[theme]
theme = "gruvbox-dark"

[theme.overrides]
separator = " "

[icons]
icons = "awesome6"

[icons.overrides]
cpu = "\uf233"

[[block]]
block = "temperature"
interval = 10
format = " $icon $average, $max"

[[block]]
block = "nvidia_gpu"
format = " $icon$utilization $memory"

[[block]]
block = "disk_space"
path = "/"
format = " / $available"
interval = 20
warning = 20.0
alert = 10.0
alert_unit = "GB"

[[block]]
block = "disk_space"
path = "/home/greg/extra_data"
format = "hdd $available"
interval = 20
warning = 20.0
alert = 10.0
alert_unit = "GB"


[[block]]
block = "memory"
format = " $icon$mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)"
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization {$frequency}"

[[block]]
block = "load"
interval = 2
format = " $icon $1m.eng(w:4)"

[[block]]
block = "time"
interval = 30
format = "上海 $timestamp.datetime(f:%R)"
timezone = "Asia/Shanghai"

[[block]]
block = "time"
interval = 30
format = "$icon $timestamp.datetime()"

[[block]]
block = "sound"
