[theme]
name = "slick"

[theme.overrides]
separator = ""

[icons]
name = "awesome"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
