[theme]
name = "modern"

[theme.overrides]
separator = ""

[icons]
name = "awesome"


[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "/ {available}"
interval = 20
warning = 10.0
alert = 5.0
alert_absolute = true

[[block]]
block = "memory"
format_mem = "{mem_used}({mem_used_percents})"
format_swap = "{swap_used}({swap_used_percents})"
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
